# -*- coding: utf-8 -*-
"""MLexp1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HpRwVz8mL91E4ju62CxSWFrK9AzEpk-1
"""

import sys
import pandas as pd
import numpy as np
import sklearn
import matplotlib
import seaborn as sns
print("Library Versions")
print("-" * 40)
print(f"Pandas         : {pd.__version__}")
print(f"NumPy          : {np.__version__}")
print(f"Scikit-learn   : {sklearn.__version__}")
print(f"Matplotlib     : {matplotlib.__version__}")
print(f"Seaborn        : {sns.__version__}")

import pandas as pd
import seaborn as sns
from pandas import read_csv
df=read_csv("placement_predict_50k Dataset.csv")

df.head(12)

df.head(10)

df.tail(10)

df.tail()

df.shape
df['StudentID']

df.columns

df.dtypes

df.dtypes.value_counts()

missing_data = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum()/len(df))*100
})

missing_data

import matplotlib.pyplot as plt
plt.figure(figsize=(10, 6))
# cbar=False hides the color bar; yticklabels=False hides row numbers for cleaner v
sns.heatmap(df.isnull(), cbar=False, yticklabels=False, cmap="viridis")
plt.title("missing")
plt.show()

duplicate_rows = df[df.duplicated()]
print(f"Total duplicate rows detected: {len(duplicate_rows)}")
print(duplicate_rows)
print("-" * 40)

df[df['AptitudeTestScore'].isnull()]

df.duplicated().sum()

df = df.drop_duplicates()

df.describe()

df["PlacementStatus"].value_counts()

(df["PlacementStatus"].value_counts(normalize=True) * 100).round(2)